# Basic configuration for the azure-ollama add-on
name: Azure Ollama
version: 0.1.17
slug: azure-ollama
description: An Azure Ollama add-on for Home Assistant
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
startup: application
boot: auto
options:
  message: "Hello from the add-on!"
  apiVersion: "2024-10-21"
  logins:
  - endpoint: http://foo.com/api
    apikey: "123456"
    model: "gpt-4o"
  - endpoint: http://foo.com/api
    apikey: "123456"
    model: "gpt-4.1"
schema:
  message: str
  apiVersion: str
  logins:
  - endpoint: str
    apikey: str
    model: str
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: HA Addon Server
homeassistant_api: false
hassio_api: false
