# Basic configuration for the azure-ollama add-on
name: Azure Ollama
version: "0.1.0"
slug: azure-ollama
description: An Azure Ollama add-on for Home Assistant
arch:
- aarch64
- amd64
- armhf
- armv7
- i386
init: false
startup: application
boot: auto
options:
  message: "Hello from the add-on!"
schema:
  message: str
