name: Google Home
version: 0.0.177
slug: google_home_local_v2
description: Google Home to Home Assistant manager
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
init: false
panel_icon: mdi:google-assistant
map:
  - config:ro
  - ssl:ro
options:
  logLevel: Debug
schema:
  logLevel: list(Debug|Info|Log|Warn|Error)
  inferWebsocketUrl: bool?
  googleServiceAccountKey: str?
  googleKeyFile: str?
  googleAgentUserId: str
  localDiscoveryPacket: str?
ports:
  8089/tcp: 8089
  3311/udp: 3311
ports_description:
  8089/tcp: HA Addon Server
  3312/udp: Google local Descovery port
homeassistant_api: true
hassio_api: false
ingress: true
ingress_port: 8089
ingress_entry: ""
