name: Google Home V2
version: 0.0.78
slug: google_home_local_v2
description: Google Home to Home Assistant manager V2
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
boot: auto
init: false
panel_icon: mdi:google-assistant
map:
  - config:ro
  - ssl:ro
options:
  logLevel: Debug
schema:
  logLevel: list(Debug|Info|Log|Warn|Error)
  inferWebsocketUrl: bool?
  googleServiceAccountKey: str?
  googleKeyFile: str?
  googleAgentUserId: str
ports:
  8089/tcp: 8089
  8090/tcp: 8090
  3312/udp: 3312
ports_description:
  8089/tcp: HA Addon Server
  8090/tcp: HA Addon Https Server
  3312/udp: Google local Descovery port
homeassistant_api: true
hassio_api: false
ingress: true
ingress_port: 8089
ingress_entry: ""
